### ISSUE TITLE
Add Tutorial Article?

### ISSUE THREAD

**Issue by drbh** [matter-labs/awesome-zero-knowledge-proofs#2]
Maybe this tutorial is useful?

It uses ZoKrates ( which uses libsnarks) in a docker container with a small Flask api to create proofs/verify via REST API

https://medium.com/@david.richard.holtz/zero-knowledge-proof-application-demo-2a457cfc73c1

<img width="1551" alt="proveit" src="https://user-images.githubusercontent.com/9896130/52961509-1cd7d400-3369-11e9-9326-fec3d5623262.png">

**Comment by gluk64** [comment]
Sorry, the notifications were not on and I just saw the issue! Please create a pull request, I'll merge it.
